######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 30 22:24:14 2013
######################################################################

TEMPLATE = app
TARGET = make 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameboard.h golutilities.h
SOURCES += gameboard.cpp golutilities.cpp showgen.cpp sim-gui.cpp sim-tui.cpp
