######################################################################
# Automatically generated by qmake (2.01a) Wed May 1 21:57:09 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamegui.h lines.h ../gameboard.h ../golutilities.h
SOURCES += gamegui.cpp \
           lines.cpp \
           sim-gui.cpp \
           ../gameboard.cpp \
           ../golutilities.cpp
